<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Faried Nurmohamed">
<meta name="author" content="Karlijn Huissen">
<meta name="author" content="Austėja Tarvydaitė">
<meta name="author" content="Marta Zolnowska">

<title>Ecological Connectivity Analysis in Delta Cities - a case study in Rotterdam and Guangzhou</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ecological Connectivity Analysis in Delta Cities - a case study in Rotterdam and Guangzhou</h1>
<p class="subtitle lead">Project report of Group A</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Faried Nurmohamed </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            MSc Geomatics
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Karlijn Huissen </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            MSc Geomatics
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Austėja Tarvydaitė </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            MSc Geomatics
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Marta Zolnowska </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            MSc Geomatics
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">None</span>This is a computational notebook
</div>
</div>
<div class="callout-body-container callout-body">
<p>Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <a href="https://quarto.org" class="uri">https://quarto.org</a>.</p>
<section id="running-code" class="level2">
<h2 class="anchored" data-anchor-id="running-code">Running Code</h2>
<p>When you click the <strong>Render</strong> button a document will be generated that includes both content and the output of embedded code. You can embed code like this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>You can add options to executable code like this</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>The <code>echo: false</code> option disables the printing of code (only output is displayed).</p>
<p>You can delete this entire callout between and including the lines</p>
<pre><code>::: callout</code></pre>
<p>and</p>
<pre><code>:::</code></pre>
<p>and start the report from the Introduction section below.</p>
</section>
</div>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Delta cities - will add context on it later</p>
<p>Rotterdam and Guangzhou represent two contrasting delta city contexts. - to be added</p>
<p>ecological connectivty in delta cities - importance issue etc. - find a research gap</p>
<p>This study addresses this gap through the following research question:</p>
<blockquote class="blockquote">
<p><em>To what extent does green infrastructure connectivity vary across urban areas in delta cities Rotterdam and Guangzhou, and what does this imply for targeted Nature-based Solutions?</em></p>
</blockquote>
<p>The main objective of this research is to develop an informed Nature-based Solutions plan tailored to spatially comparable areas in both cities. The objective is explored and pursued using following steps: (1) assessing the current status of ecological connectivity using betweenness centrality and patch connectivity analysis; (2) identifying comparable areas across both cities based on a multi-criteria clustering approach combining Local Climate Zones, connectivity metrics, and patch characteristics; (3) conducting a deeper spatial analysis of these comparable areas; and (4) proposing targeted Nature-based Solutions for them.</p>
</section>
<section id="case-study-area" class="level2">
<h2 class="anchored" data-anchor-id="case-study-area">Case Study Area</h2>
<p>This research focuses on two case studies: one in the Netherlands and one in China. The Dutch study area is the port city of Rotterdam; in China, Guangzhou was chosen. To get a better understanding of the current ecological state in both cities, we looked for datasets that map green spaces in each urban environment. For Rotterdam, we used the “Groenkaart,” developed by the Rijksinstituut voor Volksgezondheid en Milieu (RIVM) (Atlas Leefomgeving, 2024). This map shows the locations of green vegetation across the Netherlands, including trees, shrubs, and plants, and distinguishes between different types of green areas, such as agricultural land, nature, and urban green space, to show how green cover is distributed across the country.</p>
<p>Since Guangzhou is much larger in scale, we could not find a map with a comparable resolution and level of detail that would remain readable at the city scale, so we used an alternative instead. SinoLC-1, a 1-meter-resolution national-scale land-cover map of China, gave us a clear picture of where green areas are located at the city level. <a href="#fig-introduction-pair" class="quarto-xref">Figure&nbsp;1</a> presents both maps. As shown in the map of Guangzhou on the right, the main distinction is between tree cover (dark green) and built environment (dark orange). A more detailed breakdown of the classifications and legend can be found in Li et al.&nbsp;(2023), but for the purposes of this stage, this level of detail was sufficient. Together, both maps give us a general understanding of each area before we zoom in for deeper analysis.</p>
<ul>
<li>add infor about different sizes of the cities, population etc.</li>
</ul>
<div id="fig-introduction-pair" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-introduction-pair-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-introduction-pair" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-roffa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-roffa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Rotterdam_introduction.png" class="img-fluid figure-img" data-ref-parent="fig-introduction-pair">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-roffa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Rotterdam
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-introduction-pair" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-guang" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-guang-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Guangzhou_introduction.png" class="img-fluid figure-img" data-ref-parent="fig-introduction-pair">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-guang-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Guangzhou
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-introduction-pair-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: General introduction of cities.
</figcaption>
</figure>
</div>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>notes: ESA WorldCover 10m v200 - https://developers.google.com/earth-engine/datasets/catalog/ESA_WorldCover_v200#bands The European Space Agency (ESA) WorldCover 10 m 2021 product provides a global land cover map for 2021 at 10 m resolution based on Sentinel-1 and Sentinel-2 data. The WorldCover product comes with 11 land cover classes and has been generated in the framework of the ESA WorldCover project, part of the 5th Earth Observation Envelope Programme (EOEP-5) of the European Space Agency.</p>
<p>LCZ maps for Rotterdam and Guangzhou were obtained from the LCZ Generator (https://lcz-generator.rub.de/global-lcz-map)</p>
<section id="envelope" class="level4">
<h4 class="anchored" data-anchor-id="envelope">Envelope</h4>
<p>When collecting data, running analyses, and producing maps, it is important to look slightly beyond our area of interest. This is especially relevant when considering ecological connections, since important elements could lie outside our extent. To make sure we capture the surroundings of our area of interest, we therefore decided to create an envelope that extends beyond our bounding box.</p>
<p>For both Rotterdam and Guangzhou, we created a minimum bounding geometry around the shape of the city or municipality. This function can be found in the Processing Toolbox in QGIS, under “Vector Geometry.” As shown in <a href="#fig-envelope-roffa" class="quarto-xref">Figure&nbsp;2</a>, this creates an envelope around the maximum extent of the shape. To capture some additional surrounding area, we then added a 5 km buffer around this bounding box (Vector &gt; Geoprocessing Tools &gt; Buffer). This buffered envelope defines the study area used throughout the project.</p>
<div id="fig-envelope-roffa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-envelope-roffa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/envelope_rotterdam.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-envelope-roffa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Envelope creation in Rotterdam.
</figcaption>
</figure>
</div>
<p>Add same thing voor Guanzhou: <img src="images/GZintroductory.png" id="fig-envelope-intro" class="img-fluid" style="width:100.0%" alt="Envelope creation in Guanzhou"></p>
</section>
<section id="sec-spatialgrid" class="level4">
<h4 class="anchored" data-anchor-id="sec-spatialgrid">Spatial Grid</h4>
<p>A regular spatial grid of 500 × 500 m cells was constructed for each city in QGIS software (Vector Research Tools → Create Grid), covering the set envelope boundary of each city. The grid was created specifically for the typology construction process, providing a consistent spatial unit for aggregating and comparing data layers.</p>
<p>A cell size of 500 × 500 m was chosen to match the dispersal distance parameter (d = 500 m) used in the Graphab connectivity analysis (see <a href="#sec-patches" class="quarto-xref">Section&nbsp;4.2.2</a>). The same distance ensures that each cell somewhat corresponds to the spatial scale at which ecological connectivity is assessed, making the typology meaningful in relation to the crucial connectivity metrics.</p>
</section>
<section id="local-climate-zones" class="level4">
<h4 class="anchored" data-anchor-id="local-climate-zones">Local Climate Zones</h4>
<p>sources to add : https://www.wudapt.org/lcz/ https://lcz-generator.rub.de/global-lcz-map</p>
<p>In order to make a comparable the description of urban morphology across both cities, the Local Climate Zone (LCZ) classification scheme developed by Stewart and Oke (2012) was used. The classification identfies 17 zones based urban on surface structure (e.g.&nbsp;building and tree height and density) and surface cover (pervious versus impervious).</p>
<p>The LCZ typology is a universal urban classification it focuses specifically on urban and rural landscape types, distinguished through 10 built types (ranging from compact high-rise to heavy industry) and 7 land cover types (ranging from dense trees to water). Its main advantage lies in the diversity of urban classes, which are easily interpretable and globally consistent.</p>
<p><a href="#fig-lczrt" class="quarto-xref">Figure&nbsp;3</a> and <a href="#fig-lczgz" class="quarto-xref">Figure&nbsp;4</a> below, depict the distribution of Local Climate Zones in the choosen Cities.</p>
<div id="fig-lczrt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lczrt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/lcz_rt-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lczrt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Rotterdam Local Climate Zones
</figcaption>
</figure>
</div>
<div id="fig-lczgz" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lczgz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/lcz_gz-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lczgz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Guangzhou Local Climate Zones
</figcaption>
</figure>
</div>
</section>
</section>
<section id="ecological-connectivity-analysis" class="level3">
<h3 class="anchored" data-anchor-id="ecological-connectivity-analysis">Ecological Connectivity Analysis</h3>
<section id="sec-mspa" class="level4">
<h4 class="anchored" data-anchor-id="sec-mspa">Morphological Spatial Pattern Analysis</h4>
<p>Morphological Spatial Pattern Analysis (MSPA) is a series of mathematical image processing steps that help in understanding the shape and connectivity of different parts within an image. It was developed at the EU Joint Research Centre to describe the geometry and connectivity of the certain pattern in a binary image (Soille &amp; Vogt, 2009) (European Commission Joint Research Centre, n.d.). Every pixel is assigned to one of seven structural classes: Core, Islet, Perforation, Edge, Loop, Bridge, and Branch. Together they describe how connected, isolated, or marginal each part of the explored pattern is.</p>
<p>In this application, Core represents the interior of large patches of green infrastructure; Islet depicts small, isolated fragments with no core area; Perforation marks the margin of an opening or gap within a larger patch; Edge is the outer boundary zone where a patch meets the surrounding urban areas; Bridge and Loop describe narrow, corridor structures connecting two separate core areas or looping back into the same one; and Branch is narrow, dead-end attached to only one core area.</p>
<p>Since MSPA requires a binary foreground/background input, the first step was to derive such a mask from the ESA WorldCover v200 land-cover product (10 m resolution), which classifies the land surface into eleven categories: tree cover, shrubland, grassland, cropland, built-up, bare/sparse vegetation, snow/ice, permanent water bodies, herbaceous wetland, mangroves, and moss/lichen. This reclassification was carried out in Google Earth Engine, where the WorldCover layer was reclassified so that ecologically relevant classes (tree cover, shrubland, grassland, cropland, herbaceous wetland, and mangroves) were assigned a value of 1 (foreground), while built-up land, bare/sparse vegetation, permanent water bodies and snow/ice were assigned a value of 0 (background, representing the non-ecological matrix). The resulting binary raster was exported as a GeoTIFF and imported into QGIS for the MSPA analysis itself.</p>
<p>The MSPA analysis was performed in QGIS using the MSPA plugin from the European Commission’s Forest Joint Research Centre.</p>
<p>Three parameters are used in MSPA segments. Foreground connectivity, which determines whether diagonally touching pixels count as connected, was set to 8-connectivity rather than 4-connectivity, since ecological movement (animals) is not restricted to the four directions. Edge width, which sets the thickness of the buffer zone separating core area from the surrounding matrix, was set to 5 pixels; at WorldCover’s 10 m resolution this corresponds to a 50 m buffer. Transition, which determines whether bridge or loop pixels passing through an edge or perforation to a core area are shown separately, was switched on.</p>
</section>
<section id="sec-patches" class="level4">
<h4 class="anchored" data-anchor-id="sec-patches">Patches and Link Importance (through Graphab)</h4>
<p>To conduct the ecological connectivity analysis, the software of Grapnhab is used. Graphab is a software program devoted to the modelling of habitat networks using graph-theoretical approaches (Graphab, n.d.). Graph theory provides a simple solution for unifying and evaluating multiple aspects of habitat connectivity, because it can be applied at patch and landscape levels, and it quantifies either structural or functional connectivity (Minor &amp; Urban, 2008). A graph network is represented by a set of nodes and edges, where the nodes are the individual elements within a network (the patches), and edges represent the connectivity between the nodes (links). Graphab combines the construction and visualization of graphs, with subsequent connectivity analyses and links with external geographical or biological data.</p>
<p>By loading the .tiff file created by the MSPA analysis, Graphab can read the landcover classification and filter on those accordingly. We filtered on land use code “17” to select the core areas as habitat patches, Graphab then created a linkset to visualise all the possible connections between each habitat patch (to later use for the calculations).</p>
<p>After loading everything into Graphab, we then continued by making use of the weighted metrics. To understand the importance of each patch and link, two different metrics are used. Before you can run metrics calculations, you first need to create a graph. While creating the graph, we selected the linkset along with a distance threshold (by doing this, it only kept the links within this threshold). For the selected areas in Rotterdam and Guangzhou, multiple distances were tested to understand which number would give a meaningful result. With a short distance, it would result into giving too much importance to smaller links, but with a distance that is too large, it would not take the smaller links into consideration as much. We therefore landed on a value of 10 000m.</p>
<p>For the patches, delta Probability of Connectivity Index (dPC) was used. dPC measures how much overall connectivity (PC) drops when you remove a patch (Metro Vancouver, 2025). It is a metric that measures the individual contribution of a specific habitat patch to the overall connectivity of the landscape. It represents the change in the PC index when a particular patch is removed, thereby assessing the importance of that patch in maintaining landscape connectivity. This metric is composed of three components: dPCintra, a measure of intrapatch connectivity, dPCconnect, the importance of a patch for connecting other patches together, and dPCflux, a measure of how connected a patch is to the network. The sum of these fractions equals the total delta Probability of Connectivity. This calculation was sadly only available for patches in Graphab, so for the links a different metric was used.</p>
<p>The links were classified through Betweenness Centrality (BC). It counts how many patch-to-patch routes pass through each link (Estrada &amp; Bodin, 2008). It’s defined per element and works cleanly on edges, giving a differentiated value for every link: which “potential” connections act as the busiest throughways/bridges. It is a measure of how frequently a node appears on the shortest paths between pairs of other nodes in a network. Together, they formed a complete picture revealing the critical habitats and the critical corridors between them. In our research, they are used as two complementary connectivity metrics, each appropriate to its element type.</p>
<p>For both metrics, the parameters dispersal distance (d) and probability (p) are needed to compute the calculations. Both refer to the chance of an animal moving from one patch to another, based on the distance between the patches, and the dispersal characteristics of the selected animal species (Estreguil et al., 2014). During this research, a specific animal species is not be identified, so therefore we took a dispersal distance of 500 m. This is a common default for urban green infrastructure studies. It represents medium-mobility species and also roughly matches human walking distance to green space. It’s considered good for general urban ecology assessments. The probability starts at a default of 0.5, meaning “at 500 m, there is a 50% chance of successful dispersal”. This is again a standard assumption since we don’t specify species.</p>
<p>After the calculations are computed, each patch and each link now contained dPC and BC values that can be categorised and visualised in QGIS. Here, the patches are visualised through a graduated symbology from green to yellow, where dark green marks a higher value. With five classes on equal intervals, the patches are ordered in importance. Dark green therefore means that once this patch would be removed, it would impact the overall connectivity the most. The links are filtered on the 500 most important ones for each city (by selecting the 500 links with the highest BC value). They are then also visualised though a graduated symbology, this time on line thickness as well as colour. The thicker and darker the lines appear, the busiest the link appears to be in the network. Here however, all links would provide a big impact, since they are filtered on the 500 most important ones.</p>
<p>In the Results (<a href="#sec-result-ecoconnect-roffa" class="quarto-xref">Section&nbsp;5.1.2</a> and <a href="#sec-result-ecoconnect-gz" class="quarto-xref">Section&nbsp;6.1.2</a>), the outcome of this analysis for Rotterdam and Guangzhou is presented, which will be used as one of the inputs for the clustering analysis in the next section.</p>
</section>
<section id="typology-construction" class="level4">
<h4 class="anchored" data-anchor-id="typology-construction">Typology Construction</h4>
<p>After Patches and Link Importance analysis and MSPA, it is possible to develop typologies based on their outcomes for broader understanding of ecological connectity and urban/green matrix in both cities. Typology is a classification of areas based on shared combinations of characteristics (source here). To identify spatial character of ecology and its connectivity in Rotterdam and Guangzhou, a typology was constructed for both cities using the same set of variables and spatial unit, allowing direct quantitative comparison between the two cities.</p>
<p>To construct this typology, two crucial aspects need to be defined: the variables used to characterise each area, and the spatial unit at which these variables were measured. The variables used were Local Climate Zones, ecological connectivity (betweenness centrality), and green patch characteristics, as these together capture both the urban characteristics and the ecological functioning of an area. The spatial unit used was a fixed-size grid of 500 × 500 m cells (see <a href="#sec-spatialgrid" class="quarto-xref">Section&nbsp;4.1.2</a>). A fixed grid was used because it allows different variables to be aggregated and compared.</p>
<p>This typology serves as a broad ecological overview of both cities that summarises, at a coarse spatial resolution, where green connectivity is strong, where it is weak or absent, and what kind of green structure dominates each area. It is not intended to pinpoint specific intervention sites, but to provide the wider ecological context which enables more detailed analyses performed further. Combined with the MSPA and patch/link importance results (<a href="#sec-results-ecoconnect" class="quarto-xref">Section&nbsp;5.1</a>), this typology was used to guide the selection of the smaller zoom-in study areas examined in more detail later in this report.</p>
<section id="clustering" class="level5">
<h5 class="anchored" data-anchor-id="clustering">Clustering</h5>
<p>All three criteria for typologies were summarised per grid cell. Betweenness centrality values were spatially joined to the grid using an intersection, with the mean normalised BC value computed per cell. Green patch metrics (patch count and mean patch capacity, derived from the dPC field) were similarly joined to the grid. Grid cells with no links or patches passing through them were assigned a value of zero, since they simply have no green connectivity (this is not missing data but a meaningful absence).</p>
<p>Before clustering, the three numeric variables (BC mean, patch count, and mean patch capacity) were standardised using z-score normalisation to ensure equal weighting regardless of original scale. K-means clustering (k = 5) was then applied to these three standardised variables. Clustering was implemented as a reusable function in R, executed directly within the reproducible Quarto report, so that cluster assignments regenerate automatically whenever the report is rendered. Because K-means assigns cluster numbers arbitrarily, each resulting cluster was subsequently classified according to its own ecological profile into: Disconnected urban fabric (lowest combined patch presence and capacity, i.e.&nbsp;no meaningful green network), Key corridors (highest betweenness centrality), Isolated quality patches (highest patch capacity), Fragmented green (highest average patch count), and Transition zones (the remaining profile). This classification step ensures that cluster identities, labels, and map colours remain consistent both within and across cities, and across repeated renders of the report, regardless of the raw numbering K-means happens to produce on a given run.</p>
<p>After clustering, the dominant LCZ classes per cluster were checked separately to understand what kind of urban environment each cluster is typically located in. For each cluster, the three most common LCZ classes were identified, since a single dominant class rarely captures the full urban context of a 500 × 500 m cell. LCZ was deliberately excluded from the clustering input itself, since it is a categorical variable and including its numeric codes directly would have distorted the Euclidean distances used by K-means.</p>
<p>The function below implements the clustering pipeline describedabove. It standardises the betweenness centrality, patch count, patch capacity, and LCZ variables, then applies K-means clustering with five clusters. The same function is applied separately to Rotterdam and Guangzhou in the results section.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cluster_grid <span class="ot">&lt;-</span> <span class="cf">function</span>(gpkg_path, bc_col, patch_count_col, patch_cap_col, lcz_col,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                          role_to_id, role_to_color, <span class="at">k =</span> <span class="dv">5</span>, <span class="at">seed =</span> <span class="dv">42</span>) {</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  grid <span class="ot">&lt;-</span> <span class="fu">st_read</span>(gpkg_path, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># NA means "no links/patches passing through this cell" — treat as 0</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  grid <span class="ot">&lt;-</span> grid <span class="sc">|&gt;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(bc_col, patch_count_col, patch_cap_col)), <span class="sc">~</span> <span class="fu">replace_na</span>(.x, <span class="dv">0</span>)))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  features <span class="ot">&lt;-</span> grid <span class="sc">|&gt;</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(bc_col, patch_count_col, patch_cap_col)))</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  X_scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(features)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(seed)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  km <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(X_scaled, <span class="at">centers =</span> k, <span class="at">nstart =</span> <span class="dv">20</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  raw_cluster <span class="ot">&lt;-</span> km<span class="sc">$</span>cluster</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Classify each raw kmeans cluster by its profile, not its arbitrary label ---</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  raw_profile <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">raw_id   =</span> <span class="dv">1</span><span class="sc">:</span>k,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">bc_mean  =</span> <span class="fu">as.numeric</span>(<span class="fu">tapply</span>(grid[[bc_col]], raw_cluster, mean)),</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">patches  =</span> <span class="fu">as.numeric</span>(<span class="fu">tapply</span>(grid[[patch_count_col]], raw_cluster, mean)),</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">capacity =</span> <span class="fu">as.numeric</span>(<span class="fu">tapply</span>(grid[[patch_cap_col]], raw_cluster, mean))</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  remaining <span class="ot">&lt;-</span> raw_profile</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>  role_assignment <span class="ot">&lt;-</span> <span class="fu">character</span>(k)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(role_assignment) <span class="ot">&lt;-</span> <span class="fu">as.character</span>(raw_profile<span class="sc">$</span>raw_id)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Urban matrix: lowest combined patches + capacity (no green presence)</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>  urban_id <span class="ot">&lt;-</span> remaining<span class="sc">$</span>raw_id[<span class="fu">which.min</span>(remaining<span class="sc">$</span>patches <span class="sc">+</span> remaining<span class="sc">$</span>capacity)]</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>  role_assignment[<span class="fu">as.character</span>(urban_id)] <span class="ot">&lt;-</span> <span class="st">"Urban matrix"</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>  remaining <span class="ot">&lt;-</span> remaining <span class="sc">|&gt;</span> <span class="fu">filter</span>(raw_id <span class="sc">!=</span> urban_id)</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Key corridors: highest BC among what's left</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>  corridor_id <span class="ot">&lt;-</span> remaining<span class="sc">$</span>raw_id[<span class="fu">which.max</span>(remaining<span class="sc">$</span>bc_mean)]</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>  role_assignment[<span class="fu">as.character</span>(corridor_id)] <span class="ot">&lt;-</span> <span class="st">"Key corridors"</span></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>  remaining <span class="ot">&lt;-</span> remaining <span class="sc">|&gt;</span> <span class="fu">filter</span>(raw_id <span class="sc">!=</span> corridor_id)</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Isolated quality patches: highest capacity among what's left</span></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>  isolated_id <span class="ot">&lt;-</span> remaining<span class="sc">$</span>raw_id[<span class="fu">which.max</span>(remaining<span class="sc">$</span>capacity)]</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>  role_assignment[<span class="fu">as.character</span>(isolated_id)] <span class="ot">&lt;-</span> <span class="st">"Isolated quality patches"</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>  remaining <span class="ot">&lt;-</span> remaining <span class="sc">|&gt;</span> <span class="fu">filter</span>(raw_id <span class="sc">!=</span> isolated_id)</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4. Fragmented green: highest patch count among what's left</span></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>  fragmented_id <span class="ot">&lt;-</span> remaining<span class="sc">$</span>raw_id[<span class="fu">which.max</span>(remaining<span class="sc">$</span>patches)]</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>  role_assignment[<span class="fu">as.character</span>(fragmented_id)] <span class="ot">&lt;-</span> <span class="st">"Fragmented green"</span></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>  remaining <span class="ot">&lt;-</span> remaining <span class="sc">|&gt;</span> <span class="fu">filter</span>(raw_id <span class="sc">!=</span> fragmented_id)</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 5. Whatever's left</span></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>  role_assignment[<span class="fu">as.character</span>(remaining<span class="sc">$</span>raw_id)] <span class="ot">&lt;-</span> <span class="st">"Transition zones"</span></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>  <span class="co"># --- Remap to your fixed, city-specific ID and color scheme ---</span></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>  grid<span class="sc">$</span>cluster_role  <span class="ot">&lt;-</span> role_assignment[<span class="fu">as.character</span>(raw_cluster)]</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>  grid<span class="sc">$</span>cluster_id    <span class="ot">&lt;-</span> role_to_id[grid<span class="sc">$</span>cluster_role]</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>  grid<span class="sc">$</span>cluster_color <span class="ot">&lt;-</span> role_to_color[grid<span class="sc">$</span>cluster_role]</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>  profile <span class="ot">&lt;-</span> grid <span class="sc">|&gt;</span></span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(cluster_id, cluster_role) <span class="sc">|&gt;</span></span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>      <span class="at">n        =</span> <span class="fu">n</span>(),</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>      <span class="at">bc_mean  =</span> <span class="fu">round</span>(<span class="fu">mean</span>(.data[[bc_col]]), <span class="dv">4</span>),</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>      <span class="at">patches  =</span> <span class="fu">round</span>(<span class="fu">mean</span>(.data[[patch_count_col]]), <span class="dv">2</span>),</span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>      <span class="at">capacity =</span> <span class="fu">round</span>(<span class="fu">mean</span>(.data[[patch_cap_col]]), <span class="dv">4</span>),</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a>      <span class="at">.groups  =</span> <span class="st">"drop"</span></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(cluster_id)</span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a>  lcz_summary <span class="ot">&lt;-</span> grid <span class="sc">|&gt;</span></span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(cluster_id) <span class="sc">|&gt;</span></span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(.data[[lcz_col]], <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice_max</span>(n, <span class="at">n =</span> <span class="dv">3</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">grid =</span> grid, <span class="at">profile =</span> profile, <span class="at">lcz_summary =</span> lcz_summary)</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Same five colors used by both cities</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>role_to_color <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Transition zones"</span>        <span class="ot">=</span> <span class="st">"lightblue"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Key corridors"</span>            <span class="ot">=</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Urban matrix"</span>             <span class="ot">=</span> <span class="st">"gray70"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Isolated quality patches"</span> <span class="ot">=</span> <span class="st">"orange"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Fragmented green"</span>         <span class="ot">=</span> <span class="st">"yellow"</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Rotterdam: matches your original QGIS numbering exactly</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>rt_role_to_id <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Transition zones"</span>        <span class="ot">=</span> <span class="dv">0</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Key corridors"</span>            <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Urban matrix"</span>             <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Isolated quality patches"</span> <span class="ot">=</span> <span class="dv">3</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Fragmented green"</span>         <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Guangzhou: matches your original QGIS numbering exactly (different order!)</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>gz_role_to_id <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Fragmented green"</span>         <span class="ot">=</span> <span class="dv">0</span>,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Urban matrix"</span>             <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Transition zones"</span>         <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Isolated quality patches"</span> <span class="ot">=</span> <span class="dv">3</span>,</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Key corridors"</span>             <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lcz_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"1"</span>  <span class="ot">=</span> <span class="st">"LCZ 1 – Compact high-rise"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"2"</span>  <span class="ot">=</span> <span class="st">"LCZ 2 – Compact mid-rise"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"3"</span>  <span class="ot">=</span> <span class="st">"LCZ 3 – Compact low-rise"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"4"</span>  <span class="ot">=</span> <span class="st">"LCZ 4 – Open high-rise"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"5"</span>  <span class="ot">=</span> <span class="st">"LCZ 5 – Open mid-rise"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"6"</span>  <span class="ot">=</span> <span class="st">"LCZ 6 – Open low-rise"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"7"</span>  <span class="ot">=</span> <span class="st">"LCZ 7 – Lightweight low-rise"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"8"</span>  <span class="ot">=</span> <span class="st">"LCZ 8 – Large low-rise"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"9"</span>  <span class="ot">=</span> <span class="st">"LCZ 9 – Sparsely built"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"10"</span> <span class="ot">=</span> <span class="st">"LCZ 10 – Heavy industry"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"11"</span> <span class="ot">=</span> <span class="st">"LCZ A – Dense trees"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"12"</span> <span class="ot">=</span> <span class="st">"LCZ B – Scattered trees"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"13"</span> <span class="ot">=</span> <span class="st">"LCZ C – Bush, scrub"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"14"</span> <span class="ot">=</span> <span class="st">"LCZ D – Low plants"</span>,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"15"</span> <span class="ot">=</span> <span class="st">"LCZ E – Bare rock or paved"</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"16"</span> <span class="ot">=</span> <span class="st">"LCZ F – Bare soil or sand"</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"17"</span> <span class="ot">=</span> <span class="st">"LCZ G – Water"</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
</section>
<section id="study-area-selection" class="level3">
<h3 class="anchored" data-anchor-id="study-area-selection">Study Area Selection</h3>
<p>Comparable study areas between Rotterdam and Guangzhou were identified by matching clusters across both cities based on similarities in their BC values, patch characteristics, and LCZ composition. Two pairs of zoom in areas were chosen for each city.</p>
</section>
<section id="ecological-resistance" class="level3">
<h3 class="anchored" data-anchor-id="ecological-resistance">Ecological Resistance</h3>
<p>After selecting 2 study areas within each city a deeper analysis is performed to investigate barriers to ecological connectivity as well as potentials for improvement. Especially for understanding how to implement “potential” links, it’s important to take the context into account. The graph theory showcases a simplified version of reality, but all the barriers such as roads, train tracks, rivers, and many others, are not yet taken into account.</p>
<ul>
<li>add here what will be investigated (4 metrics and how we combine them)</li>
</ul>
<section id="ndvi" class="level4">
<h4 class="anchored" data-anchor-id="ndvi">NDVI</h4>
<ul>
<li>-1.0 to 0: Non-vegetated surfaces like clouds, snow, or open water.</li>
<li>0 to 0.1: Bare soil, rock, roads, or urban infrastructure.</li>
<li>0.2 to 0.5: Sparse or stressed vegetation, grasslands, or crops.</li>
<li>0.6 to 1.0: Dense, healthy vegetation such as mature forests or crops at peak growth. (source)</li>
</ul>
</section>
<section id="ndbi" class="level4">
<h4 class="anchored" data-anchor-id="ndbi">NDBI</h4>
<ul>
<li>“&gt;” 0: Likely built-up or urban areas.</li>
<li>≈ 0: Bare soil or mixed terrain.</li>
<li>&lt; 0: Vegetation (which reflects highly in NIR) or water bodies. (source)</li>
</ul>
</section>
<section id="land-use" class="level4">
<h4 class="anchored" data-anchor-id="land-use">Land Use</h4>
<p>1-5 scale 1 - low: trees/shrub 2 - low-moderate: grass/wetland 3 - moderate: cropland 4 - moderate-high:bare/water 5 - high: built-up (source)</p>
</section>
<section id="road-density" class="level4">
<h4 class="anchored" data-anchor-id="road-density">Road Density</h4>
<p>parameters: search radius: Radius of the circular neighbourhood (in meters). - 10m pixel size:Pixel size of the output raster layer in layer units(in meters).-10m (source)</p>
</section>
<section id="combining-the-layers" class="level4">
<h4 class="anchored" data-anchor-id="combining-the-layers">Combining the layers</h4>
<p>To combine all resistance layers and get a good representation of the overall ecological resistance, some extra preprocessing was needed. Each of the four input layers, NDVI, NDBI, land cover, and road density, was originally on a different value scale. For the case of Rotterdam, NDVI ranged from -0.2 to 0.8, NDBI from -0.5 to 0.5, road density from 0 to 0.15 km/km², while the land cover resistance was already classified from 1 to 5. Averaging these raw values directly would produce meaningless results, since the scales are incompatible and the ecological direction of the values differs between layers (high NDVI indicates low resistance, while high NDBI indicates high resistance).</p>
<p>Each layer was therefore reclassified into a standardised 1-to-5 ecological resistance scale using equal-interval breakpoints derived from the value range of each layer, where 1 represents the lowest resistance to species movement and 5 the highest. In the QGIS Raster Calculator, this was implemented as a conditional sum, where each condition evaluates to 0 or 1, ensuring every pixel is assigned to exactly one class:</p>
<p>(layer &gt;= threshold₄) × 1 + (layer &gt;= threshold₃ AND layer &lt; threshold₄) × 2 + (layer &gt;= threshold₂ AND layer &lt; threshold₃) × 3 + (layer &gt;= threshold₁ AND layer &lt; threshold₂) × 4 + (layer &lt; threshold₁) × 5</p>
<p>The four thresholds were calculated as min + n × (range / 5) for n = 1 through 4, dividing each layer’s value range into five equal intervals. For example, NDBI with a range of -0.5 to 0.5 produces thresholds at -0.3, -0.1, 0.1, and 0.3, assigning resistance classes 1 through 5 from lowest to highest built-up intensity. After reclassification and clipping to the study area boundary, the four layers were combined by averaging them in the QGIS Raster Calculator (adding them up and then dividing by four), producing a continuous ecological resistance surface ranging from 1 to 5. This was done for both zoom in areas in both cities, which was then overlaid with the initial “potential” links.</p>
</section>
</section>
</section>
<section id="sec-results-roffa" class="level2">
<h2 class="anchored" data-anchor-id="sec-results-roffa">Results Rotterdam</h2>
<section id="sec-results-ecoconnect" class="level3">
<h3 class="anchored" data-anchor-id="sec-results-ecoconnect">Current Ecological Connectivity Status</h3>
<section id="morphological-spatial-pattern-analysis-mspa" class="level4">
<h4 class="anchored" data-anchor-id="morphological-spatial-pattern-analysis-mspa">Morphological Spatial Pattern Analysis (MSPA)</h4>
<p>After running the MSPA analysis (<a href="#sec-mspa" class="quarto-xref">Section&nbsp;4.2.1</a>) on the Rotterdam envelope area and analysing the distribution of classes, the green network (Core, Islet, Perforation, Edge, Loop, Bridge, Branch) covers 45.77% of it, while background (the non-green matrix: Background, Core-Opening, Border-Opening) 54.23%.</p>
<p><a href="#fig-MSPArt" class="quarto-xref">Figure&nbsp;5</a> shows large green cores, but this is partly because the foreground includes a broad set of land cover classes (Tree, Shrubland, Grassland, Cropland, Wetland, and Mangroves), so some of these cores may not be fully representative of high-quality ecological habitat.</p>
<p>This is a useful basis for the patch and link importance analysis that follows (<a href="#sec-result-ecoconnect-roffa" class="quarto-xref">Section&nbsp;5.1.2</a>). The green patches should not be treated as equally meaningful nodes. MSPA analysis is dominated by small cores like the tail-like fragments (likely isolated street trees, small gardens and other small green elements. They are numerous but contribute negligibly to the total core area and are unlikely to be significant habitats on their own. However, these fragments could still matter as stepping stones for connectivity. This supports running the patch and link importance analysis specifically on the dominant core patches, since they are the backbone of the green network. Moreover, two smaller study areas within the city are also examined more closely, using metrics like NDVI, NDBI, road density, and land-cover resistance, to assess habitat quality and connectivity in more detail than the broader MSPA classification alone can provide.</p>
<div id="fig-MSPArt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-MSPArt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/RT_mspa.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-MSPArt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Morphological Spatial Pattern Analysis in Rotterdam
</figcaption>
</figure>
</div>
</section>
<section id="sec-result-ecoconnect-roffa" class="level4">
<h4 class="anchored" data-anchor-id="sec-result-ecoconnect-roffa">Patches and Link Importance</h4>
<p>To represent the ecological connectivity, the layers are split into the patches and links. For the patches, the most essential elements of the green structure are visualised in dark green and less important elements in lighter shades leading up to yellow. Higher importance in this case means that if this patch were to be removed, the connectivity of the entire network would suffer the most. Patches with higher importance can’t be supported by the surrounding green structure, meaning a greater loss in network connectivity. By focusing on an envelope around the boundary of Rotterdam, we get to include more context that would’ve been lost otherwise. This envelope shape sadly still cuts off the surrounding patches, so some patches appear smaller within this shape and in the overall connectivity therefore also score less. This is a limitation of the envelope approach, but it did help in reducing the computation time so we take this in consideration.</p>
<p>The same visualisation is done for the links, where a darker and thicker brown represents the most important “potential” links in the network. It is interesting to see that most of the links don’t run into the boundary of Rotterdam. Since the patches around the city are much bigger and get more importance, the links span around the boundary rather than within. From this analysis, it then shifts the focus on a link outside of the city boundary, but then we would lose the urban area factor that is central in our research. That’s why we chose to run the metric again but this time only within the boundary of Rotterdam, to understand which parts of the patches then become crucial and where meaningful interventions could happen in the urban environment.</p>
<div id="fig-connectivity-renvelope" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-connectivity-renvelope-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Rotterdam_connectivity_envelope.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-connectivity-renvelope-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Ecological connectivity within the Envelope.
</figcaption>
</figure>
</div>
<div id="fig-connectivity-rboundary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-connectivity-rboundary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Rotterdam_connectivity_rboundary.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-connectivity-rboundary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Ecological connectivity within the boundary of Rotterdam.
</figcaption>
</figure>
</div>
<p>As can be seen in <a href="#fig-connectivity-rboundary" class="quarto-xref">Figure&nbsp;7</a>, we can now identify spaces within the boundary of Rotterdam that could be improved. These, together with some additional analysis on clustering, will then form the basis of choosing the zoom in locations.</p>
</section>
<section id="cluster-profiles" class="level4">
<h4 class="anchored" data-anchor-id="cluster-profiles">Cluster Profiles</h4>
<p>K-means clustering of Rotterdam’s grid cells produced five ecological profiles. Table X presents the mean values per cluster for betweenness centrality, patch count, and patch capacity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>rt <span class="ot">&lt;-</span> <span class="fu">cluster_grid</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/rt_grid_clustering.gpkg"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">bc_col          =</span> <span class="st">"new_normal"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">patch_count_col =</span> <span class="st">"dpc_total_"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">patch_cap_col   =</span> <span class="st">"dpc_tota_2"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lcz_col         =</span> <span class="st">"majortity_lcz_grid__majority"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">role_to_id      =</span> rt_role_to_id,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">role_to_color   =</span> role_to_color</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(rt<span class="sc">$</span>profile, <span class="at">caption =</span> <span class="st">"Rotterdam cluster profiles"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Rotterdam cluster profiles</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 37%">
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">cluster_id</th>
<th style="text-align: left;">cluster_role</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">bc_mean</th>
<th style="text-align: right;">patches</th>
<th style="text-align: right;">capacity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Transition zones</td>
<td style="text-align: right;">2266</td>
<td style="text-align: right;">0.0092</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.0348</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Key corridors</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">0.6243</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">0.2519</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Urban matrix</td>
<td style="text-align: right;">3175</td>
<td style="text-align: right;">0.0005</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Isolated quality patches</td>
<td style="text-align: right;">497</td>
<td style="text-align: right;">0.0029</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">0.3742</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Fragmented green</td>
<td style="text-align: right;">759</td>
<td style="text-align: right;">0.0087</td>
<td style="text-align: right;">2.21</td>
<td style="text-align: right;">0.0248</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Cluster 2 (Urban matrix) is the largest group in Rotterdam (n = 3,175, around 47% of all grid cells), representing areas with no meaningful green network (neither patches nor betweenness centrality are present in these cells). Cluster 1 (Key corridors) is the smallest (n = 83) but the most ecologically significant. These are key corridor locations, combining the highest betweenness centrality of any cluster (BC mean = 0.6243) with moderate-to-high patch capacity. Cluster 3 (Isolated quality patches, n = 497) captures high-quality green patches that are poorly connected to the wider network (the lowest BC but the highest patch capacity). Cluster 4 (Fragmented green, n = 759) represents fragmented green space: cells here contain multiple small, low-capacity patches (2.21 per cell on average) with minimal connectivity. Cluster 0 (Transition zones, n = 2,266) is a lower-density version of fragmented green (typically a single small, low-quality patch per cell with weak connectivity) situated between the urban matrix and the more clearly green-dominated clusters (look at map…).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>rt<span class="sc">$</span>lcz_summary <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lcz_label =</span> lcz_labels[<span class="fu">as.character</span>(majortity_lcz_grid__majority)]) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cluster_id, <span class="fu">desc</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster_id) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rank  =</span> <span class="fu">paste0</span>(<span class="st">"Rank "</span>, <span class="fu">row_number</span>()),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">entry =</span> <span class="fu">paste0</span>(lcz_label, <span class="st">" (n="</span>, n, <span class="st">")"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cluster_id, rank, entry) <span class="sc">|&gt;</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> rank, <span class="at">values_from =</span> entry) <span class="sc">|&gt;</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cluster_id) <span class="sc">|&gt;</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Top LCZ classes per Rotterdam cluster"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top LCZ classes per Rotterdam cluster</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 27%">
<col style="width: 30%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">cluster_id</th>
<th style="text-align: left;">Rank 1</th>
<th style="text-align: left;">Rank 2</th>
<th style="text-align: left;">Rank 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">LCZ D – Low plants (n=1104)</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=372)</td>
<td style="text-align: left;">LCZ 8 – Large low-rise (n=301)</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">LCZ D – Low plants (n=75)</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=3)</td>
<td style="text-align: left;">LCZ 8 – Large low-rise (n=3)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">NA (n=1468)</td>
<td style="text-align: left;">LCZ 8 – Large low-rise (n=476)</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=367)</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">LCZ D – Low plants (n=347)</td>
<td style="text-align: left;">LCZ A – Dense trees (n=37)</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=32)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">LCZ D – Low plants (n=299)</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=195)</td>
<td style="text-align: left;">LCZ B – Scattered trees (n=107)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The dominant LCZ classes per cluster depict a clear contrast between Rotterdam’s green network and its urban matrix. LCZ D (Low plants) is the most common class in every cluster except the Urban matrix (including the Key corridors cluster (75 of 83 cells), the Transition zones cluster (1,104 cells), the Isolated quality patches cluster (347 cells), and the Fragmented green cluster (299 cells)). This indicates that nearly all of Rotterdam’s green connectivity network runs through open, low-vegetation land such as grassland and polder. The Urban matrix cluster stands apart entirely: its top classes are LCZ 8 (Large low-rise, 476 cells) and LCZ 6 (Open low-rise, 367 cells); which are pure built environments. A few secondary classes point to where Rotterdam’s denser tree cover sits. The Isolated quality patches cluster is the only one with a meaningful presence of LCZ A (Dense trees, 37 cells), suggesting its highest-capacity green patches include some wooded areas alongside open vegetation. The Fragmented green cluster shows the strongest secondary presence of LCZ B (Scattered trees, 107 cells), consistent with a patchwork of small green elements that includes some tree cover rather than open land alone.</p>
<section id="spatial-distribution" class="level5">
<h5 class="anchored" data-anchor-id="spatial-distribution">Spatial Distribution</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">9</span>))  <span class="co"># extra right-hand margin reserved for the legend</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(rt<span class="sc">$</span>grid), <span class="at">col =</span> rt<span class="sc">$</span>grid<span class="sc">$</span>cluster_color, <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">main =</span> <span class="cn">NULL</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="fu">par</span>(<span class="st">"usr"</span>)[<span class="dv">2</span>], <span class="at">y =</span> <span class="fu">par</span>(<span class="st">"usr"</span>)[<span class="dv">4</span>],</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(role_to_color), <span class="at">fill =</span> role_to_color,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">xpd =</span> <span class="cn">NA</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/rt-map-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Rotterdam — spatial distribution of clusters</figcaption>
</figure>
</div>
</div>
</div>
<p>The spatial distribution map depicts that the isolated quality patches cluster forms one large, contiguous zone in the southwest of Rotterdam (with the open, low-vegetation polder landscape identified in the LCZ analysis). The Key corridors cluster runSdirectly along its southern edge, its only substantial concentration anywhere in the study area. The remainder of the map is dominated by a mix of Urban matrix cells interspersed with Transition zones and Fragmented green, with no further concentrations of either Isolated quality patches or Key corridors elsewhere in Rotterdam.</p>
</section>
</section>
</section>
</section>
<section id="sec-results-gz" class="level2">
<h2 class="anchored" data-anchor-id="sec-results-gz">Results Guangzhou</h2>
<section id="sec-results-ecoconnect2" class="level3">
<h3 class="anchored" data-anchor-id="sec-results-ecoconnect2">Current Ecological Connectivity Status</h3>
<section id="morphological-spatial-pattern-analysis-mspa-1" class="level4">
<h4 class="anchored" data-anchor-id="morphological-spatial-pattern-analysis-mspa-1">Morphological Spatial Pattern Analysis (MSPA)</h4>
<p>After running the Morphological Spatial Pattern Analysis on Guangzhou’s envelope area (Section 4.2.1) and analysing the distribution of classes, the overall result is similar to Rotterdam, though slightly less green-dominated. The backround covers the majority of the evenelope’s area accounting for 58.19% as opposed to the overall green network (Core, Islet, Perforation, Edge, Loop, Bridge, Branch) covering 41.81% (approximately 4% lower than Rotterdam).@fig-MSPAgz highlights a large and continuous green network in the North part of the envelope with majority of the cores located there. As with Rotterdam, these areas include a number of different types of vegetation, however trees (value 10) are the most dominant ones.</p>
<div id="fig-MSPAgz" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-MSPAgz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/GZ_mspa.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-MSPAgz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Morphological Spatial Pattern Analysis in Guangzhou
</figcaption>
</figure>
</div>
</section>
<section id="sec-result-ecoconnect-gz" class="level4">
<h4 class="anchored" data-anchor-id="sec-result-ecoconnect-gz">Patches and Link Importance</h4>
<div id="fig-connectivity-first" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-connectivity-first-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/FirstGZmap.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-connectivity-first-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Ecological connectivity within the Envelope.
</figcaption>
</figure>
</div>
<div id="fig-connectivity-second" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-connectivity-second-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Second_GZmap.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-connectivity-second-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Ecological connectivity within the boundary of Guangzhou
</figcaption>
</figure>
</div>
</section>
<section id="cluster-profiles-1" class="level4">
<h4 class="anchored" data-anchor-id="cluster-profiles-1">Cluster Profiles</h4>
<p>K-means clustering of Guangzhou’s grid cells produced five ecological profiles. Table X presents the mean values per cluster for betweenness centrality, patch count, and patch capacity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>gz <span class="ot">&lt;-</span> <span class="fu">cluster_grid</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/gz_grid_clustering.gpkg"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">bc_col          =</span> <span class="st">"bc_d500_p0.5_beta1_graph10000_mean"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">patch_count_col =</span> <span class="st">"dpc_sum_count"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">patch_cap_col   =</span> <span class="st">"dpc_sum_mean"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lcz_col         =</span> <span class="st">"lcz_majority_grids_lcz__majority"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">role_to_id      =</span> gz_role_to_id,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">role_to_color   =</span> role_to_color</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(gz<span class="sc">$</span>profile, <span class="at">caption =</span> <span class="st">"Guangzhou cluster profiles"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Guangzhou cluster profiles</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 37%">
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">cluster_id</th>
<th style="text-align: left;">cluster_role</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">bc_mean</th>
<th style="text-align: right;">patches</th>
<th style="text-align: right;">capacity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Fragmented green</td>
<td style="text-align: right;">760</td>
<td style="text-align: right;">0.4115</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">0.0123</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Urban matrix</td>
<td style="text-align: right;">1502</td>
<td style="text-align: right;">0.0008</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Transition zones</td>
<td style="text-align: right;">713</td>
<td style="text-align: right;">0.0049</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">0.0223</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Isolated quality patches</td>
<td style="text-align: right;">406</td>
<td style="text-align: right;">0.0588</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">0.4227</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Key corridors</td>
<td style="text-align: right;">1455</td>
<td style="text-align: right;">0.4281</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.0212</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Guangzhou’s clustering reveals a different ecological pattern from Rotterdam. Cluster 1 (urban matrix, n = 1,502) has no patches and no connectivity, which is comparable in role to Rotterdam’s largest cluster (also urban matrix). However, it is proportionally much smaller (about 31% of cells here, versus 47% in Rotterdam) which reflects Guangzhou’s denser green network. Cluster 4 (Key corridors, n = 1,455) and Cluster 0 (Fragmented green, n = 760) both show high betweenness centrality (BC mean around 0.41–0.43), indicating that high-connectivity corridors are far more widespread in Guangzhou than in Rotterdam. Cluster 0 combines high BC with the highest average patch count of any cluster (3.00 per cell), suggesting fragmented but well-connected green space. Cluster 3 (Isolated quality patches, n = 406) is the clearest cross-city match: like Rotterdam’s equivalent, it shows the highest patch capacity of any Guangzhou cluster (0.4227) alongside comparatively low BC (0.0588). Cluster 2 (Transition zones, n = 713) shows a low-quality green presence with weak connectivity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: gz-lcz</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>gz<span class="sc">$</span>lcz_summary <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lcz_label =</span> lcz_labels[<span class="fu">as.character</span>(lcz_majority_grids_lcz__majority)]) <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cluster_id, <span class="fu">desc</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster_id) <span class="sc">|&gt;</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rank  =</span> <span class="fu">paste0</span>(<span class="st">"Rank "</span>, <span class="fu">row_number</span>()),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">entry =</span> <span class="fu">paste0</span>(lcz_label, <span class="st">" (n="</span>, n, <span class="st">")"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cluster_id, rank, entry) <span class="sc">|&gt;</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> rank, <span class="at">values_from =</span> entry) <span class="sc">|&gt;</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cluster_id) <span class="sc">|&gt;</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Top LCZ classes per Guangzhou cluster"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top LCZ classes per Guangzhou cluster</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">cluster_id</th>
<th style="text-align: left;">Rank 1</th>
<th style="text-align: left;">Rank 2</th>
<th style="text-align: left;">Rank 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=346)</td>
<td style="text-align: left;">LCZ 8 – Large low-rise (n=218)</td>
<td style="text-align: left;">LCZ 4 – Open high-rise (n=63)</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">LCZ 8 – Large low-rise (n=580)</td>
<td style="text-align: left;">LCZ 4 – Open high-rise (n=221)</td>
<td style="text-align: left;">NA (n=192)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">LCZ A – Dense trees (n=186)</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=175)</td>
<td style="text-align: left;">LCZ 8 – Large low-rise (n=175)</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">LCZ A – Dense trees (n=351)</td>
<td style="text-align: left;">LCZ 6 – Open low-rise (n=41)</td>
<td style="text-align: left;">LCZ B – Scattered trees (n=6)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">LCZ 8 – Large low-rise (n=541)</td>
<td style="text-align: left;">LCZ 4 – Open high-rise (n=239)</td>
<td style="text-align: left;">LCZ A – Dense trees (n=205)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In Guangzhou, the Isolated quality patches cluster is dominated by LCZ A (Dense trees, 351 of 406 cells — 86%), proving it to be a forest rather than open vegetation. The Transition zones cluster is also led by LCZ A (Dense trees, 186 cells), though more evenly mixed with LCZ 6 (Open low-rise, 175 cells) and LCZ 8 (Large low-rise, 175 cells), suggesting a blend of wooded and low-rise built contexts. The Key corridors cluster is dominated by LCZ 8 (Large low-rise, 541 cells) and LCZ 4 (Open high-rise, 239 cells), with LCZ A (Dense trees, 205 cells). This is a notable contrast with Rotterdam, where the equivalent Key corridors cluster ran almost entirely through LCZ D (open, low-vegetation land); in Guangzhou, the busiest ecological corridors instead cut through dense, large low-rise and high-rise urban fabric, implying these links function more as built-environment green threads than open-landscape pathways. The Fragmented green cluster follows the same built-dominated pattern, led by LCZ 6 (Open low-rise, 346 cells) and LCZ 8 (Large low-rise, 218 cells), with no tree-cover class appearing in its top three at all.</p>
<section id="spatial-distribution-1" class="level5">
<h5 class="anchored" data-anchor-id="spatial-distribution-1">Spatial Distribution</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">9</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(gz<span class="sc">$</span>grid), <span class="at">col =</span> gz<span class="sc">$</span>grid<span class="sc">$</span>cluster_color, <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">main =</span> <span class="cn">NULL</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="fu">par</span>(<span class="st">"usr"</span>)[<span class="dv">2</span>], <span class="at">y =</span> <span class="fu">par</span>(<span class="st">"usr"</span>)[<span class="dv">4</span>],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">names</span>(role_to_color), <span class="at">fill =</span> role_to_color,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">xpd =</span> <span class="cn">NA</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/gz-map-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Guangzhou — spatial distribution of clusters</figcaption>
</figure>
</div>
</div>
</div>
<p>The spatial distribution map shows the Isolated quality patches cluster forms a single, large block in the north of the study area, consistent with the dense, forested LCZ A landscape identified in the LCZ analysis. Unlike Rotterdam, where the key corridors cluster formed one narrow line along the edge of the isolated patches, Guangzhou’s Key corridors cluster forms an extensive, web-like network spanning most of the lower two-thirds of the study area, intertwined with fragmented green cells. This reflects Guangzhou’s much larger high-connectivity network, running primarily through the built urban fabric. The urban matrix cluster and transition zones cells fill the remaining gaps, more concentrated toward the southwestern part of the envelope.</p>
</section>
</section>
</section>
</section>
<section id="sec-results-comp" class="level2">
<h2 class="anchored" data-anchor-id="sec-results-comp">Comparing Results</h2>
<section id="comparable-study-areas" class="level3">
<h3 class="anchored" data-anchor-id="comparable-study-areas">Comparable Study Areas</h3>
<p>Two pairs of comparable areas were identified based on similarity in ecological connectivity profiles and urban context.</p>
<p>Rather than matching individual clusters one-to-one between cities, comparable study areas were identified by examining the spatial distribution of cluster types within each city’s own grid. In both cities, the isolated quality patches cluster (high-capacity green space with weak connectivity) was used as the starting point, since it represents the clearest opportunity for targeted connectivity intervention: ecologically valuable green space that is currently disconnected from the wider network. The immediate surroundings of these patches were examined to understand what type of green (or absence of it) borders them.</p>
</section>
<section id="zoom-ins-rotterdam" class="level3">
<h3 class="anchored" data-anchor-id="zoom-ins-rotterdam">Zoom Ins Rotterdam</h3>
<p><a href="#fig-zoomin-roffa" class="quarto-xref">Figure&nbsp;11</a> presents the two zoom-in locations selected for Rotterdam, chosen for their comparability. The context of the two tiles, however, is very different: zoom-in 1 focuses on a heavily industrialised area at the Port of Rotterdam, while zoom-in 2 examines a neighbourhood situated at the boundary of the municipality. The additional analysis conducted on these smaller tiles is presented in the next section.</p>
<div id="fig-zoomin-roffa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-zoomin-roffa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Rotterdam_zoomin_intro.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-zoomin-roffa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Zoom in locations in Rotterdam
</figcaption>
</figure>
</div>
<p>also this has to be edited: Here we see that the orange cluster showing good quality patches with weak connectivty is surrounded mostly by framgmented low quality greens (cluster 2) and some 0 clusters (Transition zones — moderate connectivity, some patches) and there is some green (cluster 1), which indicate a small but significant presence of key corridors with very high BC and quality patches. This depict potential that the cluster 1 could be expanded (by leverging parts of orange cluster or connecting yellow areas (also improving their quality) around it. But then when looking at the whole ecological profile of rotterdam there are not any mor eorange clusters withing the area, which could motivate the second intervention (on yellow clusters with id 2) in other areas (maybe top right corner of the envelope).</p>
<p>study area 1 has 22647834,561 m2 and second has 36012716,54162598 m2.</p>
<section id="ecological-resistance-1" class="level4">
<h4 class="anchored" data-anchor-id="ecological-resistance-1">Ecological Resistance</h4>
<section id="ndvi-1" class="level5">
<h5 class="anchored" data-anchor-id="ndvi-1">NDVI</h5>
<p>The min-max you had : -0.2 to 0.8 values ##### NDBI The min-max you had : -0.5 to 0.5 values ##### Land Use ##### Road Density The min-max you had : 0 to 0,15</p>
</section>
<section id="ndbi-1" class="level5">
<h5 class="anchored" data-anchor-id="ndbi-1">NDBI</h5>
</section>
<section id="land-use-1" class="level5">
<h5 class="anchored" data-anchor-id="land-use-1">Land Use</h5>
</section>
<section id="road-density-1" class="level5">
<h5 class="anchored" data-anchor-id="road-density-1">Road Density</h5>
<div id="fig-ecores-roffa1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecores-roffa1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/eco_resistance_roffa1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecores-roffa1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Ecological resistance analysis layers zoom in 1.
</figcaption>
</figure>
</div>
<div id="fig-ecores-roffa2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecores-roffa2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/eco_resistance_roffa2.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecores-roffa2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Ecological resistance analysis layers zoom in 2.
</figcaption>
</figure>
</div>
</section>
<section id="conclusion-maps" class="level5">
<h5 class="anchored" data-anchor-id="conclusion-maps">Conclusion Maps</h5>
<p>After combining all layers, the barriers facing each “potential” link become clear. As shown in the bottom map of each figure, some “potential” links already follow an existing green corridor or element; from this stage onward, we therefore focus only on the missing links.</p>
<p>In zoom-in 1, the dominant barrier is the Nieuwe Waterweg, a key shipping channel serving the Port of Rotterdam. The thinner barriers in this area are also waterways, reflecting its role as part of the Europoort of Rotterdam. When developing NBS in the next step, this industrial character and port functionality must be taken into account.</p>
<p>Zoom-in 2 sits at the edge of the city, where residential neighbourhoods become the focus. The barriers here are correspondingly different: highways, roads, and railway tracks are the obstacles that need to be overcome.</p>
<div id="fig-ecores-tot-roffa1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecores-tot-roffa1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/total_eco_resistance_roffa1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecores-tot-roffa1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Ecological resistance zoom in 1 (layers combined).
</figcaption>
</figure>
</div>
<div id="fig-ecores-tot-roffa2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecores-tot-roffa2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/total_eco_resistance_roffa2.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecores-tot-roffa2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Ecological resistance zoom in 2 (layers combined).
</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="zoom-ins-guangzhou" class="level3">
<h3 class="anchored" data-anchor-id="zoom-ins-guangzhou">Zoom Ins Guangzhou</h3>
<p><img src="images/Third_GZmap.png" id="fig-zoomin-gz" class="img-fluid" style="width:100.0%" alt="Zoom in locations in Guangzhou"> Figure 16 presents the two zoom-in locations selected for Guangzhou. The selection was guided primarily by link importance: areas concentrating the highest-importance links (very high and high, visible as the darkest, thickest lines on the map) were prioritised, as these represent the most critical missing connections in the network. To ensure comparability with the Rotterdam zoom-in areas in terms of spatial scale and analytical accuracy, the size of each tile was kept consistent with those selected for Rotterdam, with district boundaries taken into account when defining the extents.</p>
<p>The two zoom-in areas reflect contrasting urban contexts within Guangzhou. Zoom-in 1 is located in the northern part of the study area, in the Tianhe District, where the landscape transitions toward hillier, more vegetated terrain. This area contains a concentration of very high and high importance links connecting green patches across a mixed urban-natural gradient. Zoom-in 2 is situated further south, in the Haizhu District, where the urban character is denser and more built-up. Here, the critical links run through a more fragmented urban fabric, presenting a different set of barriers and opportunities for Nature-based Solutions compared to zoom-in 1.</p>
<section id="ecological-resistance-2" class="level4">
<h4 class="anchored" data-anchor-id="ecological-resistance-2">Ecological Resistance</h4>
<section id="ndvi-2" class="level5">
<h5 class="anchored" data-anchor-id="ndvi-2">NDVI</h5>
</section>
<section id="ndbi-2" class="level5">
<h5 class="anchored" data-anchor-id="ndbi-2">NDBI</h5>
</section>
<section id="land-use-2" class="level5">
<h5 class="anchored" data-anchor-id="land-use-2">Land Use</h5>
</section>
<section id="road-density-2" class="level5">
<h5 class="anchored" data-anchor-id="road-density-2">Road Density</h5>
<div id="fig-zoom1-metrics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-zoom1-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/zoom1_metrics.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-zoom1-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Ecological resistance analysis layers zoom in 1.
</figcaption>
</figure>
</div>
<div id="fig-zoom2-metrics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-zoom2-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/zoom2_metrics.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-zoom2-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Ecological resistance analysis layers zoom in 2.
</figcaption>
</figure>
</div>
</section>
<section id="conclusion-maps-1" class="level5">
<h5 class="anchored" data-anchor-id="conclusion-maps-1">Conclusion Maps</h5>
<div id="fig-resistance-first" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resistance-first-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/zoom1_resistance.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resistance-first-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Ecological resistance zoom in 1 (layers combined).
</figcaption>
</figure>
</div>
<div id="fig-resistance-second" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resistance-second-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/zoom2_resistance_final.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resistance-second-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: Ecological resistance zoom in 2 (layers combined).
</figcaption>
</figure>
</div>
</section>
</section>
</section>
</section>
<section id="nature-based-solutions" class="level2">
<h2 class="anchored" data-anchor-id="nature-based-solutions">Nature-based Solutions</h2>
<p>To identify where Nature-based Solutions can most effectively improve ecological connectivity, the maps combining ecological resistance and link importance (Figures 14, 15, 18, 19) were used as the primary analytical basis. For each zoom-in area, the links with the highest betweenness centrality were overlaid with the combined ecological resistance surface. Where these high-importance links cross zones of very high resistance, shown in red on the maps, these intersections were identified as the critical barrier locations requiring intervention. For each of these locations, the underlying land use was then determined, as the nature of the barrier directly defines which NbS are feasible. This process was applied consistently across all four zoom-in areas, ensuring that the proposed NbS are spatially grounded rather than generically applied, and that they reflect the specific urban context of each location, ranging from industrial port infrastructure and residential neighbourhoods in Rotterdam to mixed urban-natural terrain and dense riverine fabric in Guangzhou.</p>
<section id="rotterdam-zoom-in-1" class="level3">
<h3 class="anchored" data-anchor-id="rotterdam-zoom-in-1">Rotterdam: Zoom-in 1</h3>
<p>Overlaying the highest-importance links with the combined ecological resistance surface in zoom-in area 1 (Figure 14) shows that the most critical link crosses zones of very high resistance concentrated around the Nieuwe Waterweg and the surrounding port terminal surfaces. Examining the underlying land use reveals two distinct barrier types: the open shipping channel of the Nieuwe Waterweg itself, and the impervious built-up surfaces of the industrial port infrastructure on either side.</p>
<p>For the industrial port surfaces, where high resistance is driven by impervious cover and near-absent vegetation, hybrid and adaptive edge solutions are proposed. This involves introducing native vegetation along quay edges and installing ecological habitat modules on existing hard port infrastructure bordering the link corridor. Marzio et al.&nbsp;(2025) identify this approach, retrofitting waterfront edges with hybrid green-grey solutions, as one of the three core NbS strategies for urban waterfronts, noting that such solutions allow natural processes to operate within built environments, providing a flexible approach in space-constrained areas without interfering with primary port functions.</p>
<p>For the secondary harbour basins and quieter dock edges along the link corridor, constructed floating wetlands (FTWs) are proposed as aquatic stepping stones. Rome et al.&nbsp;(2023) demonstrate that FTWs planted with native species provide valuable wetland habitat and produce localised improvements in ecological quality even at small scales. Critically, Rome et al.&nbsp;(2023) also note that very few studies have explored FTWs in active urban waterways that continue to support industrial transportation, directly confirming that placement within the main Nieuwe Waterweg shipping channel is not feasible. FTWs are therefore proposed exclusively for quieter secondary basins, at intervals not exceeding 500 m, consistent with the dispersal distance used throughout this study.</p>
<p>The main Nieuwe Waterweg channel itself constitutes a residual hard barrier that cannot be addressed through NbS. Active large-vessel navigation makes any in-channel intervention physically hazardous and infeasible, and this limitation should be acknowledged in broader connectivity planning for Rotterdam.</p>
</section>
<section id="rotterdam-zoom-in-2" class="level3">
<h3 class="anchored" data-anchor-id="rotterdam-zoom-in-2">Rotterdam: Zoom-in 2</h3>
<p>Overlaying the highest-importance links with the combined ecological resistance surface in zoom-in area 2 (Figure 15) shows that the most critical links cross zones of very high resistance concentrated along a network of roads, highways and railway lines running through the residential urban fabric. Unlike zoom-in 1, the wider matrix here shows moderate to low resistance, suggesting that the surrounding residential area already contains meaningful green elements; the primary connectivity problem is the fragmentation caused by these transport corridors cutting across the link trajectories.</p>
<p>For the road and railway barriers, two complementary NbS are proposed. First, green verges and roadside vegetation enhancement along the transport corridors that the critical links cross. Cork et al.&nbsp;(2024) demonstrate in a systematic review that road and railway verges in temperate zones have significant potential for habitat connectivity, particularly for generalist species, and that verge habitat quality and continuity are key determinants of their effectiveness as ecological corridors. Enhancing existing verges through native planting, reduced mowing regimes, and structural diversification can meaningfully reduce resistance along these corridors without requiring major infrastructure changes. Second, for locations where the highest-importance links cross major roads or rail lines and verge enhancement alone is insufficient, green bridges or crossing structures are proposed as a more targeted intervention. Cork et al.&nbsp;(2024) also note that successful dispersal across railways requires specific crossing provisions, and that such structures are increasingly being integrated into transport infrastructure planning as credible NbS alternatives.</p>
<p>For the residential matrix between the transport barriers, where resistance is already moderate to low, pocket parks and street tree networks are proposed to strengthen connectivity between existing green patches, reducing the effective ecological distance between the larger green areas visible in the northwest of the zoom-in area and the patches further east.</p>
</section>
<section id="guangzhou-zoom-in-1" class="level3">
<h3 class="anchored" data-anchor-id="guangzhou-zoom-in-1">Guangzhou: Zoom-in 1</h3>
<p>Overlaying the highest-importance links with the combined ecological resistance surface in zoom-in area 1 (Figure 18) shows that the overall resistance in the Tianhe District is predominantly very low to low, reflecting large and continuous patches of subtropical forest. However, the highest-importance links cross several broader zones of moderate to high resistance: wider patches of urban fabric with buildings, paved surfaces and limited vegetation that interrupt the otherwise continuous forest matrix. Within these urban zones, red lines indicate that roads add an additional layer of very high resistance. The barrier to connectivity is therefore a combination of urban built fabric and the roads embedded within it.</p>
<p>Two complementary NbS are proposed. First, for the roads within the urban fabric, vegetated wildlife underpasses are proposed at the specific locations where the highest-importance links cross them. As demonstrated for Rotterdam zoom-in 2, Cork et al.&nbsp;(2024) confirm that native vegetation at and around crossing structures significantly increases their use by wildlife, and that verge continuity guides species movement toward crossing points. Given the subtropical forest context, underpasses should connect directly to existing forest edge vegetation on both sides.</p>
<p>Second, for the broader urban fabric zones between the forest patches, green roofs, green walls and pocket parks are proposed as stepping stone NbS to increase the permeability of the urban matrix along the link corridors (<a href="#fig-greenroofs" class="quarto-xref">Figure&nbsp;20</a>). Madre et al.&nbsp;(2018) show that green roofs and green walls can function as stepping stones in fragmented urban areas, enhancing species dispersal through the urban matrix. This is further supported by Joshi &amp; Teller (2021), whose systematic review explicitly identifies green roofs as a medium for connecting urban green areas, providing potential for habitat connectivity and maintenance of the ecological network. Importantly, Joshi &amp; Teller (2021) note that building height is a determining factor for biodiversity effectiveness, and call for future research to include taller buildings in ecological network analyses, a relevant consideration given the high-rise character of parts of the Tianhe urban fabric. Green roofs should therefore be prioritised on lower-rise buildings along the link trajectory, where their connectivity potential is greatest.</p>
<div id="fig-greenroofs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-greenroofs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/greenroofs.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-greenroofs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: Schematic representing the diverse processes involved in conventional roofs and green roofs (Joshi &amp; Teller, 2021).
</figcaption>
</figure>
</div>
<p>Together these two interventions address both barrier types: the roads through targeted crossing structures, and the urban matrix through a network of distributed green stepping stones.</p>
</section>
<section id="guangzhou-zoom-in-2" class="level3">
<h3 class="anchored" data-anchor-id="guangzhou-zoom-in-2">Guangzhou: Zoom-in 2</h3>
<p>Overlaying the highest-importance links with the combined ecological resistance surface in zoom-in area 2 (Figure 19) reveals a fragmented landscape where existing parks (very low resistance, dark green) are separated by three distinct barrier types: a large river channel running diagonally through the area, roads visible as red lines of very high resistance, and broader zones of moderate to high resistance representing dense urban fabric between the parks.</p>
<p>Three complementary NbS are proposed. First, for the river channel and its banks, riparian vegetation restoration is proposed along both margins where the critical links cross the waterway. Machado &amp; Kim (2024) demonstrate that restoring native riparian vegetation along urban stream corridors directly improves ecological quality and connectivity function, creating a continuous vegetated margin that allows species to move parallel to and across the waterway via existing bridges and culverts.</p>
<p>Second, for the roads where very high resistance is visible as red lines, vegetated road verges and crossing enhancements are proposed, as previously described for Rotterdam zoom-in 2 and Guangzhou zoom-in 1 (Cork et al., 2024), at the specific locations where critical links intersect them.</p>
<p>Third, for the broader urban fabric zones of moderate to high resistance between the parks, green roofs and green walls are proposed as stepping stone NbS along the link trajectories. As described for Guangzhou zoom-in 1 (Madre et al., 2018; Joshi &amp; Teller, 2021), these interventions increase the permeability of the urban matrix along the critical link corridors. The connectivity potential of green roofs is particularly strong in Haizhu given its relatively low-rise urban fabric compared to Tianhe, since Joshi &amp; Teller (2021) specifically note that lower buildings support more effective biodiversity outcomes from green roof implementation.</p>
<p>Together these three interventions directly target all identified resistance barriers, the river, the roads, and the urban matrix, along the trajectories of the highest-importance links connecting the existing park patches.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="conefor-vs.-graphab" class="level3">
<h3 class="anchored" data-anchor-id="conefor-vs.-graphab">Conefor vs.&nbsp;Graphab</h3>
<p>Limitation of Conefor vs Graphahb, long computation time, time lost, results not as expected…</p>
</section>
<section id="differences-and-similarities-between-cities" class="level3">
<h3 class="anchored" data-anchor-id="differences-and-similarities-between-cities">Differences and similarities between cities</h3>
</section>
<section id="implications-for-nbs" class="level3">
<h3 class="anchored" data-anchor-id="implications-for-nbs">Implications for NbS</h3>
</section>
</section>
<section id="recommendations-further-research" class="level2">
<h2 class="anchored" data-anchor-id="recommendations-further-research">Recommendations &amp; Further Research</h2>
<ul>
<li>How NbS would improve connectivity (re-running ecological connectivty analysis with NBS intervations purposed) - or if we have time we can do it after NBS chapter</li>
</ul>
</section>
<section id="ai-statement" class="level2">
<h2 class="anchored" data-anchor-id="ai-statement">AI Statement</h2>
</section>
<section id="reference-list" class="level2">
<h2 class="anchored" data-anchor-id="reference-list">Reference List</h2>
<p>Atlas Leefomgeving. (2024). Groenkaart van Nederland. https://www.atlasleefomgeving.nl/groenkaart-van-nederland</p>
<p>Cork, N. A., Fisher, R. S., Strong, N., Ferranti, E. J. S., &amp; Quinn, A. D. (2024). A systematic review of factors influencing habitat connectivity and biodiversity along road and rail routes in temperate zones. Frontiers in Environmental Science, 12, 1369072. https://doi.org/10.3389/fenvs.2024.1369072</p>
<p>Estrada, E., &amp; Bodin, Ö. (2008). Using network centrality measures to manage landscape connectivity. Ecological Applications, 18(7), 1810–1825. https://doi.org/10.1890/07-1419.1</p>
<p>Estreguil, C., Caudullo, G., &amp; de Rigo, D. (2014). Connectivity of Natura 2000 forest sites in Europe. F1000Posters, 5, 485. https://doi.org/10.6084/m9.figshare.1063300</p>
<p>European Commission, Joint Research Centre. (n.d.). MSPA. Forest. Retrieved June 18, 2026, from https://forest.jrc.ec.europa.eu/en/activities/lpa/mspa/</p>
<p>Graphab. (n.d.). Graphab. https://thema.umlp.fr/productions/software/graphab/en/home.html</p>
<p>Joshi, M. Y., &amp; Teller, J. (2021). Urban integration of green roofs: Current challenges and perspectives. Sustainability, 13(22), 12378. https://doi.org/10.3390/su132212378</p>
<p>Machado, J. T., &amp; Kim, G. (2024). Ecological landscape assessment of restored urban stream to guide adaptive management. Heliyon, 10(13), e33880. https://doi.org/10.1016/j.heliyon.2024.e33880</p>
<p>Madre, F., Vergnes, A., Machon, N., &amp; Clergeau, P. (2018). Green roofs and green walls for biodiversity conservation: A contribution to urban connectivity? Sustainability, 10(4), 985. https://doi.org/10.3390/su10040985</p>
<p>Marzio, S., Tosi, J., Poggi, F., &amp; Amado, M. (2025). Nature-based solutions for urban waterfront regeneration: a systematic review of frameworks, strategies and applications. City and Environment Interactions, 29, 100281. https://doi.org/10.1016/j.cacint.2025.100281</p>
<p>Metro Vancouver. (2025). Evaluation of regional ecosystem connectivity. https://metrovancouver.org/services/regional-planning/Documents/evaluation-of-regional-ecosystem-connectivity.pdf</p>
<p>Minor, E. S., &amp; Urban, D. L. (2008). A graph-theory framework for evaluating landscape connectivity and conservation planning. Conservation Biology, 22(2), 297–307. https://doi.org/10.1111/j.1523-1739.2007.00871.x</p>
<p>Rome, M., Happel, A., Dahlenburg, C., Nicodemus, P., Schott, E., Mueller, S., Lovell, K., &amp; Beighley, R. E. (2023). Application of floating wetlands for the improvement of degraded urban waters: Findings from three multi-year pilot-scale installations. Science of the Total Environment, 877, 162669. https://doi.org/10.1016/j.scitotenv.2023.162669</p>
<p>Soille, P., &amp; Vogt, P. (2009). Morphological segmentation of binary patterns. Pattern Recognition Letters, 30(4), 456–459. https://doi.org/10.1016/j.patrec.2008.10.015</p>
<p>Zhuohong Li, Wei He, Mofan Cheng, Jingxin Hu, Xiao An, Yan Huang, Guangyi Yang, &amp; Hongyan Zhang. (2023). SinoLC-1: the first 1-meter resolution national-scale land-cover map of China created with the deep learning framework and open-access data (User guide V2.4) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.8214871</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>